[package]
name = "haqq-grpc"
version = "0.1.1"
edition = "2021"
license = "MIT"
keywords = ["haqq", "cosmos", "evmos", "grpc", "proto"]
categories = ["finance", "cryptography::cryptocurrencies", "api-bindings", "asynchronous"]
description = "gRPC client for Haqq nodes"
documentation = "https://docs.rs/haqq-grpc"
repository = "https://github.com/haqq-network/haqq-clients"
readme = "README.md"
homepage = "https://haqq.network"

[dependencies]
derive_builder = "0.12.0"
ethnum = {version = "1.5.0", features = ["serde"]}
pbjson = "0.6.0"
prost = "0.12.1"
prost-wkt-types = { version = "0.5.0", features = ["vendored-protox"] }
rust_decimal = "1.33.1"
serde = "1.0.192"
tonic = "0.10.2"

[dev-dependencies]
color-eyre = "0.6"
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
# haqq-rest = {path = "./rest"}

[workspace]

members = [
".",
"haqq-build",
# "rest"
]

[features]
default = ["proto_full", "grpc"]
grpc = []
# @@protoc_deletion_point(features)
# This section is automatically generated by protoc-gen-prost-crate.
# Changes in this area may be lost on regeneration.
proto_full = ["cosmos_app_module_v1alpha1","cosmos_app_v1alpha1","cosmos_auth_v1beta1","cosmos_authz_v1beta1","cosmos_bank_v1beta1","cosmos_base_abci_v1beta1","cosmos_base_kv_v1beta1","cosmos_base_query_v1beta1","cosmos_base_reflection_v1beta1","cosmos_base_reflection_v2alpha1","cosmos_base_snapshots_v1beta1","cosmos_base_store_v1beta1","cosmos_base_tendermint_v1beta1","cosmos_base_v1beta1","cosmos_capability_v1beta1","cosmos_crisis_v1beta1","cosmos_crypto_ed25519","cosmos_crypto_hd_v1","cosmos_crypto_keyring_v1","cosmos_crypto_multisig","cosmos_crypto_multisig_v1beta1","cosmos_crypto_secp256k1","cosmos_crypto_secp256r1","cosmos_distribution_v1beta1","cosmos_evidence_v1beta1","cosmos_feegrant_v1beta1","cosmos_genutil_v1beta1","cosmos_gov_v1","cosmos_gov_v1beta1","cosmos_group_v1","cosmos_mint_v1beta1","cosmos_msg_v1","cosmos_orm_module_v1alpha1","cosmos_orm_v1","cosmos_orm_v1alpha1","cosmos_params_v1beta1","cosmos_slashing_v1beta1","cosmos_staking_v1beta1","cosmos_tx_signing_v1beta1","cosmos_tx_v1beta1","cosmos_upgrade_v1beta1","cosmos_vesting_v1beta1","cosmos_proto","ethermint_crypto_v1_ethsecp256k1","ethermint_evm_v1","ethermint_feemarket_v1","ethermint_types_v1","evmos_epochs_v1","evmos_erc20_v1","haqq_coinomics_v1","haqq_vesting_v1","tendermint_abci","tendermint_crypto","tendermint_libs_bits","tendermint_p2p","tendermint_types","tendermint_version"]
cosmos_app_module_v1alpha1 = []
cosmos_app_v1alpha1 = []
cosmos_auth_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_authz_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_bank_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_base_abci_v1beta1 = ["tendermint_abci"]
cosmos_base_kv_v1beta1 = []
cosmos_base_query_v1beta1 = []
cosmos_base_reflection_v1beta1 = []
cosmos_base_reflection_v2alpha1 = []
cosmos_base_snapshots_v1beta1 = []
cosmos_base_store_v1beta1 = []
cosmos_base_tendermint_v1beta1 = ["cosmos_base_query_v1beta1","tendermint_p2p","tendermint_types","tendermint_version"]
cosmos_base_v1beta1 = []
cosmos_capability_v1beta1 = []
cosmos_crisis_v1beta1 = ["cosmos_base_v1beta1"]
cosmos_crypto_ed25519 = []
cosmos_crypto_hd_v1 = []
cosmos_crypto_keyring_v1 = []
cosmos_crypto_multisig = []
cosmos_crypto_multisig_v1beta1 = []
cosmos_crypto_secp256k1 = []
cosmos_crypto_secp256r1 = []
cosmos_distribution_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_evidence_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_feegrant_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_genutil_v1beta1 = []
cosmos_gov_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_gov_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_group_v1 = ["cosmos_base_query_v1beta1"]
cosmos_mint_v1beta1 = []
cosmos_msg_v1 = []
cosmos_orm_module_v1alpha1 = []
cosmos_orm_v1 = []
cosmos_orm_v1alpha1 = []
cosmos_params_v1beta1 = []
cosmos_slashing_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_staking_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1","tendermint_types"]
cosmos_tx_signing_v1beta1 = []
cosmos_tx_v1beta1 = ["cosmos_base_abci_v1beta1","cosmos_base_query_v1beta1","cosmos_base_v1beta1","cosmos_tx_signing_v1beta1","tendermint_types"]
cosmos_upgrade_v1beta1 = []
cosmos_vesting_v1beta1 = ["cosmos_auth_v1beta1","cosmos_base_v1beta1"]
cosmos_proto = []
ethermint_crypto_v1_ethsecp256k1 = []
ethermint_evm_v1 = ["cosmos_base_query_v1beta1"]
ethermint_feemarket_v1 = []
ethermint_types_v1 = ["cosmos_auth_v1beta1"]
evmos_epochs_v1 = ["cosmos_base_query_v1beta1"]
evmos_erc20_v1 = ["cosmos_bank_v1beta1","cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
haqq_coinomics_v1 = ["cosmos_base_v1beta1"]
haqq_vesting_v1 = ["cosmos_base_v1beta1","cosmos_vesting_v1beta1"]
tendermint_abci = ["tendermint_crypto","tendermint_types"]
tendermint_crypto = []
tendermint_libs_bits = []
tendermint_p2p = []
tendermint_types = ["tendermint_crypto","tendermint_version"]
tendermint_version = []
## @@protoc_insertion_point(features)