name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - run: exit 0

  build:
    name: Build and check if there is no git diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
          cachixArgs: -j 8 --accept-flake-config
      - uses: cachix/cachix-action@v12
        with:
          name: haqq
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest --accept-flake-config
      - name: Run restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: CI
        run: devenv shell ci
        env:
          COSMOS_GRPC_URL: ${{ secrets.COSMOS_GRPC_URL }}
          COSMOS_REST_URL: ${{ secrets.COSMOS_REST_URL }}
