name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - run: exit 0

  build:
    name: Build and check if there is no git diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: haqq-network/nix-action@master
        with:
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          installDevenv: true
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: CI
        run: devenv shell ci
        env:
          COSMOS_GRPC_URL: ${{ secrets.COSMOS_GRPC_URL }}
          COSMOS_REST_URL: ${{ secrets.COSMOS_REST_URL }}
